### ISSUE TITLE
图片展示有bug

### ISSUE THREAD

**Issue by xhzengAIB** [wenzhaot/InstagramPhotoPicker#1]
@wenzhaot 
你好！当我选择一个使用系统相机拍出来的照片，图片的方向却不对了！这个可能对你有帮助https://github.com/xhzengAIB/DBCamera/blob/master/DBCamera/Categories/UIImage%2BCrop.m#L33

**Comment by wenzhaot** [comment]
能否具体描述一下？？？

**Comment by xhzengAIB** [comment]
你可以run在手机上，然后看看上下部分的图片，就会发现问题了！

**Comment by wenzhaot** [comment]
@xhzengAIB 确实横向的照片有问题，已修改，欢迎更新代码！

**Comment by xhzengAIB** [comment]
更新了就好！谢谢了！
