### ISSUE TITLE
There will be a padding between topView and CollectionView 

### ISSUE THREAD

**Issue by dreamgo** [wenzhaot/InstagramPhotoPicker#13]
I add a navigationController to the photoPickerView, However, there will a padding between topView and collectionView. I tried to adjust the collection position to fix it, however, when I scroll the view or tap dragbar. the padding will be return back. Any idea?

Thanks! 
![screen shot 2015-04-27 at 2 16 38 pm](https://cloud.githubusercontent.com/assets/6346870/7354246/1e2410ba-ece8-11e4-88b7-597561070cf4.png)

**Comment by wenzhaot** [comment]
```
    TWPhotoPickerController *photoPicker = [[TWPhotoPickerController alloc] init];

    photoPicker.cropBlock = ^(UIImage *image) {
        //do something
        self.imageView.image = image;
    };

    UINavigationController *navCon = [[UINavigationController alloc] initWithRootViewController:photoPicker];
    [navCon setNavigationBarHidden:YES];

    [self presentViewController:navCon animated:YES completion:NULL];
```

**Comment by dreamgo** [comment]
Thanks for your reply. It works well. However , when I commented out this line 
[navCon setNavigationBarHidden:YES];
the problem still exists.  What I need in my project is always keep the navBar. 
Any idea? thanks.

**Comment by dreamgo** [comment]
Whatever the problems can be fixed by adding navbar to each subview.
