### ISSUE TITLE
Support Multiple Selection

### ISSUE THREAD

**Issue by toftof** [wenzhaot/InstagramPhotoPicker#5]
Hey this may not be an issue. Does this control support multiple selections?

**Comment by wenzhaot** [comment]
What features do you want?

**Comment by toftof** [comment]
Can i select multiple image at one go? Or just one at a time

**Comment by wenzhaot** [comment]
It's not a good idea for this picker, because it has a crop view. How to show then in crop view when you select multipe images?

**Comment by JesseGuoX** [comment]
https://github.com/uzysjung/UzysAssetsPickerController may help, multiple selections

**Comment by toftof** [comment]
@Gingit thanks for the link
