### ISSUE TITLE
Display all assets

### ISSUE THREAD

**Issue by alexrmacleod** [wenzhaot/InstagramPhotoPicker#6]
I dragged the project files into my session and been playing around with the loadPhotos function. But can't seem to make it load up all the photos from a persons photos library. any help appreciated! whenever I change the "ALAssetsGroupSavedPhotos" to anything else I get no photos!

**Comment by wenzhaot** [comment]
May be it has no photos in your selected group type?

**Comment by alexrmacleod** [comment]
Did some research... IOS8 uses a new photo framework. PHPhotoLibrary etc... ALAssetsLibrary only works with IOS7 and below. And chance you could update it? I'm struggling to any help appreciated.

**Comment by wenzhaot** [comment]
Really？ALAssetsLibrary works with iOS8 very fine!
I will consider PHPhotoLibrary later.
